name = "SimpleGrad"
uuid = "837eacb2-5a76-4cde-be3a-83fe353b65ae"
authors = ["Mike Saint-Antoine <mikest@udel.edu>"]
version = "0.2.2"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6 - 1"

[targets]
test = ["Test"]
